// Generated by CoffeeScript 1.10.0
(function() {
  var argv, domain, files, uiSitemaps;

  argv = require('yargs').demand('domain').argv;

  files = argv._;

  domain = argv.domain;

  console.log('Files:', files);

  console.log('Domain:', domain);

  uiSitemaps = require('./index');

  uiSitemaps(domain, files, function(err, sitemap, withParams) {
    if (err != null) {
      throw err;
    }
    console.log('--- sitemap ---');
    console.log('');
    console.log(sitemap);
    console.log('');
    console.log('--- states/urls with params ---');
    return console.log(withParams);
  });

}).call(this);
