// Generated by CoffeeScript 1.10.0

/*
 * Flatten an array of arrays of arrays of...
 */

(function() {
  var flatten;

  flatten = function(array) {
    var result;
    if (!Array.isArray(array)) {
      return [array];
    }
    result = [];
    array.forEach(function(item) {
      return flatten(item).forEach(function(subItem) {
        return result.push(subItem);
      });
    });
    return result;
  };

  module.exports = flatten;

}).call(this);
