// Generated by CoffeeScript 1.10.0
(function() {
  var async, createSiteMap, stateToUrlParser;

  stateToUrlParser = require('./stateToUrlParser');

  async = require('async');

  createSiteMap = require('./createSiteMap');

  module.exports = function(domain, paths, complete) {
    var parseStates, parseXml, separateParamUrls;
    parseStates = function(cb) {
      return stateToUrlParser(paths, function(err, data) {
        var noUrl, stateToUrl;
        if (err != null) {
          return cb(err);
        }
        noUrl = data.noUrl, stateToUrl = data.stateToUrl;
        return cb(null, stateToUrl);
      });
    };
    separateParamUrls = function(stateToUrl, cb) {
      var noParams, state, url, withParams;
      withParams = {};
      noParams = {};
      for (state in stateToUrl) {
        url = stateToUrl[state];
        if (url.indexOf(':') !== -1 || url.indexOf('{') !== -1) {
          withParams[state] = url;
        } else {
          noParams[state] = url;
        }
      }
      return cb(null, withParams, noParams);
    };
    parseXml = function(withParams, noParams, cb) {
      return createSiteMap(domain, noParams, function(err, xmlString) {
        if (err != null) {
          return cb(err);
        }
        return cb(null, xmlString, withParams);
      });
    };
    return async.waterfall([parseStates, separateParamUrls, parseXml], complete);
  };

}).call(this);
