// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(obj) {
    var key, res, val;
    res = {};
    for (key in obj) {
      val = obj[key];
      res[key] = val;
    }
    return res;
  };

}).call(this);
